---
name: "Model Information"
description: "Report a model name and mapping for proper display."
labels: "Feature,needs-triage"
body:
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have enabled debug logging for my installation.
        required: true
      - label: I have filled out the issue template to the best of my ability.
        required: true
      - label: This issue only contains 1 model (if you have multiple models, open one issue for each issue).
        required: true
      - label: This issue is not a duplicate issue of any [previous issues](https://github.com/andyrak/hacs-aladdin-legacy/issues?q=is%3Aissue+label%3A%22Bug%22+)..
        required: true
- type: textarea
  attributes:
    label: "API model details"
    description: |
      "After turning on debug logging, paste a snippet from the `[API] Found device:` log message here, with only the `model`, `family`, and `vendor` fields."
      "For example: `'model': '02', 'family': 2, 'vendor': 'GENIE',`"
    render: text
  validations:
    required: true
- type: input
  attributes:
    label: "Aladdin Connect Model Name"
    description: |
      "The model name of your device, as shown in the Aladdin Connect UI."
      "Example: ![image](https://zipline.arakulo.us/u/best-sophisticated-australiankestrel.jpeg)"
  validations:
    required: true
